"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { useRoleContext } from "@/context/RoleContext";

type Candidate = { staff_id: string; staff_name: string; address_city: string; email: string | null; phone: string | null; retirement_date: string | null; staff_kind: "manager" | "contract" | "other"; reentry_blacklisted: boolean; last_reentry_invitation_at: string | null };
type Settings = { email_subject: string; email_body: string; sms_body: string };
const DEFAULT: Settings = { email_subject: "ファミーユから再応募のご案内", email_body: "〇〇さん\n\n以前はファミーユで勤務いただきありがとうございました。\n\n現在ファミーユでは、以前勤務されていた方の再応募を歓迎しています。\n\n働き方や勤務できる時間が以前と変わっていても大丈夫です。\nまたファミーユで働いてみたい、少し話を聞いてみたいという場合は、Re-entryページからお申し込みください。\n\n【Re-entryはこちら】\n{{reentry_url}}\n\nファミーユ ヘルパーサービス", sms_body: "ファミーユです。以前勤務された方へ再応募のご案内です。また働いてみたい方はこちら：{{reentry_url}}" };
const GSM7 = /^[\x0A\x0D\x20-\x7E¥èéùìòÇ\nØø\rÅåΔ_ΦΓΛΩΠΨΣΘΞÆæßÉ !\"#¤%&'()*+,\-./0-9:;<=>?@A-ZÄÖÑÜ§¿a-zäöñüà]*$/;
function smsInfo(text: string) { const gsm = GSM7.test(text); const units = gsm ? [...text].reduce((n, c) => n + "^{}\\[~]|€".includes(c) ? 2 : n + 1, 0) : [...text].reduce((n, c) => n + (c.codePointAt(0)! > 0xffff ? 2 : 1), 0); const single = gsm ? 160 : 70; const joined = gsm ? 153 : 67; const segments = units <= single ? 1 : Math.ceil(units / joined); return { units, segments, max: joined * 2, encoding: gsm ? "GSM-7" : "UCS-2" }; }
function dateText(value: string | null) { return value ? new Date(value).toLocaleDateString("ja-JP") : "—"; }

export default function ReentryRecruitmentPage() {
  const { role, loading: roleLoading } = useRoleContext();
  const [items, setItems] = useState<Candidate[]>([]); const [settings, setSettings] = useState<Settings>(DEFAULT); const [selected, setSelected] = useState<Set<string>>(new Set());
  const [lastFilter, setLastFilter] = useState("all"); const [kind, setKind] = useState("all"); const [city, setCity] = useState("all"); const [blackFilter, setBlackFilter] = useState("exclude"); const [retirementFrom, setRetirementFrom] = useState(""); const [retirementTo, setRetirementTo] = useState("");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [progress, setProgress] = useState("");
  const token = useCallback(async () => (await supabase.auth.getSession()).data.session?.access_token ?? "", []);
  const load = useCallback(async () => { setLoading(true); try { const t = await token(); const r = await fetch("/api/admin/reentry-recruitment", { headers: { Authorization: `Bearer ${t}` }, cache: "no-store" }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setItems(data.candidates ?? []); setSettings(data.settings ? { email_subject: data.settings.email_subject, email_body: data.settings.email_body, sms_body: data.settings.sms_body } : DEFAULT); } catch (e) { setMessage(e instanceof Error ? e.message : "読み込みに失敗しました"); } finally { setLoading(false); } }, [token]);
  useEffect(() => { if (role === "admin" || role === "manager") void load(); }, [role, load]);
  const cities = useMemo(() => [...new Set(items.map(x => x.address_city).filter(Boolean))].sort(), [items]); const filtered = useMemo(() => items.filter(x => { if (kind !== "all" && x.staff_kind !== kind) return false; if (city !== "all" && x.address_city !== city) return false; if (blackFilter === "exclude" && x.reentry_blacklisted) return false; if (blackFilter === "only" && !x.reentry_blacklisted) return false; if (retirementFrom && (!x.retirement_date || x.retirement_date < retirementFrom)) return false; if (retirementTo && (!x.retirement_date || x.retirement_date > retirementTo)) return false; const d = x.last_reentry_invitation_at ? (Date.now() - new Date(x.last_reentry_invitation_at).getTime()) / 86400000 : Infinity; return lastFilter === "unsent" ? !x.last_reentry_invitation_at : lastFilter === "30" ? d >= 30 : lastFilter === "90" ? d >= 90 : lastFilter === "180" ? d >= 180 : true; }), [items, kind, city, blackFilter, retirementFrom, retirementTo, lastFilter]);
  const sms = smsInfo(settings.sms_body); const canSend = selected.size > 0 && sms.segments <= 2 && !saving;
  async function saveSettings() { setSaving(true); try { const t = await token(); const r = await fetch("/api/admin/reentry-recruitment", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${t}` }, body: JSON.stringify({ action: "settings", emailSubject: settings.email_subject, emailBody: settings.email_body, smsBody: settings.sms_body }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setMessage("テンプレートを保存しました。"); } catch (e) { setMessage(e instanceof Error ? e.message : "保存に失敗しました"); } finally { setSaving(false); } }
  async function blacklist(staffId: string, value: boolean) { const t = await token(); const r = await fetch("/api/admin/reentry-recruitment", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${t}` }, body: JSON.stringify({ action: "blacklist", staffId, blacklisted: value }) }); if (!r.ok) { setMessage("ブラックリストの保存に失敗しました"); return; } setItems(xs => xs.map(x => x.staff_id === staffId ? { ...x, reentry_blacklisted: value } : x)); if (value) setSelected(s => { const n = new Set(s); n.delete(staffId); return n; }); }
  async function send() { if (!canSend || !confirm(`Re-entry案内を送信します\n\n対象：${selected.size}名\nEmail優先で送信し、即時エラー時はSMSへフォールバックします。`)) return; setSaving(true); const ids = [...selected]; const total = { requested: 0, excluded: 0, emailAccepted: 0, smsFallback: 0, failed: 0 }; try { for (let offset = 0; offset < ids.length; offset += 25) { setProgress(`Re-entry案内を送信しています… ${Math.min(offset + 25, ids.length)} / ${ids.length}`); const t = await token(); const r = await fetch("/api/admin/reentry-recruitment", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${t}` }, body: JSON.stringify({ staffIds: ids.slice(offset, offset + 25), emailSubject: settings.email_subject, emailBody: settings.email_body, smsBody: settings.sms_body }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); for (const key of Object.keys(total) as Array<keyof typeof total>) total[key] += data.summary[key] ?? 0; } setMessage(`送信対象：${total.requested} / Email受付：${total.emailAccepted} / SMS fallback：${total.smsFallback} / 失敗：${total.failed}${total.excluded ? ` / 除外：${total.excluded}` : ""}`); setSelected(new Set()); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "送信に失敗しました"); } finally { setProgress(""); setSaving(false); } }
  if (roleLoading || loading) return <main className="p-6">読み込んでいます…</main>; if (role !== "admin" && role !== "manager") return <main className="p-6">このページへのアクセス権限がありません。</main>;
  return <main className="min-h-screen bg-slate-50 p-4 md:p-6"><div className="mx-auto max-w-7xl space-y-5"><header><h1 className="text-2xl font-bold">Re-entry募集</h1><p className="mt-1 text-sm text-slate-600">退職済みスタッフへ、再応募フォームをご案内します。</p></header>{message && <div className="rounded border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{message}</div>}
    <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6"><select value={lastFilter} onChange={e => setLastFilter(e.target.value)} className="rounded border p-2"><option value="all">最終送付日：すべて</option><option value="unsent">未送付</option><option value="30">30日以上</option><option value="90">90日以上</option><option value="180">半年以上</option></select><select value={kind} onChange={e => setKind(e.target.value)} className="rounded border p-2"><option value="all">区分：すべて</option><option value="manager">マネジャー</option><option value="contract">契約社員</option><option value="other">その他</option></select><select value={city} onChange={e => setCity(e.target.value)} className="rounded border p-2"><option value="all">市区町村：すべて</option>{cities.map(c => <option key={c}>{c}</option>)}</select><select value={blackFilter} onChange={e => setBlackFilter(e.target.value)} className="rounded border p-2"><option value="exclude">ブラックリストを除外</option><option value="all">ブラックリストも表示</option><option value="only">ブラックリストのみ</option></select><input type="date" value={retirementFrom} onChange={e => setRetirementFrom(e.target.value)} className="rounded border p-2"/><input type="date" value={retirementTo} onChange={e => setRetirementTo(e.target.value)} className="rounded border p-2"/></div><p className="mt-3 text-sm font-medium">{filtered.length}名</p></section>
    <section className="rounded-xl border bg-white p-4 shadow-sm space-y-3"><label className="block text-sm font-medium">Email件名<input value={settings.email_subject} onChange={e => setSettings(s => ({ ...s, email_subject: e.target.value }))} className="mt-1 w-full rounded border p-2 font-normal"/></label><label className="block text-sm font-medium">Email本文<textarea rows={8} value={settings.email_body} onChange={e => setSettings(s => ({ ...s, email_body: e.target.value }))} className="mt-1 w-full rounded border p-2 font-normal"/></label><label className="block text-sm font-medium">SMS fallback本文<textarea rows={3} value={settings.sms_body} onChange={e => setSettings(s => ({ ...s, sms_body: e.target.value }))} className="mt-1 w-full rounded border p-2 font-normal"/></label><p className={`text-sm ${sms.segments > 2 ? "text-red-600" : "text-slate-600"}`}>文字数：{sms.units}（{sms.encoding}） / SMS：{sms.segments} segments（最大 {sms.max}文字・2 segments）</p><button onClick={saveSettings} disabled={saving} className="rounded bg-slate-700 px-4 py-2 text-sm font-semibold text-white disabled:bg-slate-400">テンプレートを保存</button></section>
    <section className="rounded-xl border bg-white shadow-sm overflow-hidden"><div className="flex flex-wrap gap-3 p-4"><button onClick={() => setSelected(new Set(filtered.filter(x => !x.reentry_blacklisted).map(x => x.staff_id)))} className="rounded border px-3 py-2 text-sm">表示中をすべて選択</button><button onClick={() => setSelected(new Set())} className="rounded border px-3 py-2 text-sm">すべて解除</button><button onClick={send} disabled={!canSend} className="rounded bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:bg-slate-400">{saving ? "送信しています…" : `一斉送付（${selected.size}名）`}</button>{progress && <span className="self-center text-sm text-slate-600">{progress}</span>}</div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-slate-100 text-left"><tr>{["今回","名前","住所","退職日","区分","Email","携帯","Black","最終案内"].map(x => <th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{filtered.map(x => <tr key={x.staff_id} className="border-t"><td className="p-3"><input type="checkbox" disabled={x.reentry_blacklisted} checked={selected.has(x.staff_id)} onChange={e => setSelected(s => { const n = new Set(s); if (e.target.checked) n.add(x.staff_id); else n.delete(x.staff_id); return n; })}/></td><td className="p-3 font-medium">{x.staff_name}</td><td className="p-3">{x.address_city || "—"}</td><td className="p-3">{dateText(x.retirement_date)}</td><td className="p-3">{x.staff_kind === "manager" ? "マネジャー" : x.staff_kind === "contract" ? "契約社員" : "その他"}</td><td className="p-3">{x.email || "—"}</td><td className="p-3">{x.phone || "—"}</td><td className="p-3"><input type="checkbox" checked={x.reentry_blacklisted} onChange={e => void blacklist(x.staff_id, e.target.checked)}/></td><td className="p-3">{dateText(x.last_reentry_invitation_at)}</td></tr>)}</tbody></table></div></section>
  </div></main>;
}
