"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabaseClient";
import { Button } from "@/components/ui/button";

type Row = { id: number; holiday_date: string; weekly_shift_id: number; shift_id: number | null; client_id: string; client_name: string; status: string; action_note: string | null; shift?: { shift_start_time: string; shift_end_time: string } | null; weekly_shift?: { start_time: string; end_time: string; holiday_off: boolean } | null };
type Holiday = { id: number; holiday_date: string; holiday_name: string; is_active?: boolean; counts: Record<string, number> };
export default function HolidayShiftsPage() {
  const [holidays, setHolidays] = useState<Holiday[]>([]); const [rows, setRows] = useState<Row[]>([]); const [selected, setSelected] = useState<string>(""); const [loading, setLoading] = useState(true); const [name, setName] = useState(""); const [date, setDate] = useState("");
  const token = async () => (await supabase.auth.getSession()).data.session?.access_token;
  const load = async () => { setLoading(true); const t = await token(); const r = await fetch("/api/holiday-shifts", { headers: t ? { Authorization: `Bearer ${t}` } : {} }); const j = await r.json(); setHolidays(j.holidays ?? []); setRows(j.rows ?? []); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const act = async (row: Row, status: string) => { const t = await token(); const r = await fetch("/api/holiday-shifts", { method: "POST", headers: { "Content-Type": "application/json", ...(t ? { Authorization: `Bearer ${t}` } : {}) }, body: JSON.stringify({ type: "action", holiday_date: row.holiday_date, weekly_shift_id: row.weekly_shift_id, shift_id: row.shift_id, client_id: row.client_id, status }) }); if (!r.ok) alert((await r.json()).error ?? "更新に失敗しました"); else await load(); };
  const addHoliday = async () => { const t = await token(); const r = await fetch("/api/holiday-shifts", { method: "POST", headers: { "Content-Type": "application/json", ...(t ? { Authorization: `Bearer ${t}` } : {}) }, body: JSON.stringify({ type: "master", holiday_date: date, holiday_name: name }) }); if (!r.ok) alert("祝日の登録に失敗しました"); else { setDate(""); setName(""); await load(); } };
  const visible = selected ? rows.filter(r => r.holiday_date === selected) : [];
  return <main className="p-6 space-y-6"><h1 className="text-2xl font-bold">祝日シフト確認</h1><section className="flex gap-2 items-end"><label>日付<input className="border p-2 block" type="date" value={date} onChange={e => setDate(e.target.value)} /></label><label>祝日名<input className="border p-2 block" value={name} onChange={e => setName(e.target.value)} /></label><Button onClick={() => void addHoliday()}>祝日を登録</Button></section><section className="border rounded p-4"><h2 className="font-semibold mb-3">祝日一覧</h2><div className="space-y-2">{holidays.map(h => <button className={`block w-full text-left p-2 rounded ${selected === h.holiday_date ? "bg-blue-100" : "bg-slate-50"}`} key={h.id} onClick={() => setSelected(h.holiday_date)}>{h.holiday_date} {h.holiday_name}　未処理 {h.counts.pending ?? 0} / 削除済 {h.counts.deleted ?? 0} / 実施 {h.counts.keep ?? 0} / 変更 {h.counts.changed ?? 0}</button>)}</div></section>{selected && <section><h2 className="font-semibold mb-3">{selected} 対象シフト</h2>{loading ? <p>読込中…</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>利用者</th><th>通常時間</th><th>月間シフト</th><th>状況</th><th>操作</th></tr></thead><tbody>{visible.map(r => <tr className="border-t" key={r.id}><td className="p-2">{r.client_name}</td><td className="p-2">{r.weekly_shift?.start_time?.slice(0,5)}～{r.weekly_shift?.end_time?.slice(0,5)}</td><td className="p-2">{r.shift ? <Link className="text-blue-600 underline" href={`/portal/roster/monthly?cs=${encodeURIComponent(r.client_id)}&month=${r.holiday_date.slice(0,7)}`}>{r.shift.shift_start_time?.slice(0,5)}～{r.shift.shift_end_time?.slice(0,5)}</Link> : "なし"}</td><td className="p-2">{r.status}</td><td className="p-2 flex gap-1">{r.status === "pending" && <><Button size="sm" variant="destructive" onClick={() => void act(r, "deleted")}>祝日休みとして削除</Button><Button size="sm" onClick={() => void act(r, "keep")}>この日は実施</Button><Button size="sm" variant="outline" onClick={() => void act(r, "changed")}>対応済み</Button></>}</td></tr>)}</tbody></table></div>}</section>}</main>;
}
