'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabaseClient';

type Definition = { id: string; name: string; job_type: string; execution_mode: string; trigger_type: string; is_enabled: boolean; schedule: { timezone?: string; times?: string[] }; payload: Record<string, unknown>; last_generated_at: string | null };

export default function RpaJobDefinitionsPage() {
  const [rows, setRows] = useState<Definition[]>([]); const [message, setMessage] = useState('');
  async function headers() { const { data } = await supabase.auth.getSession(); if (!data.session?.access_token) throw new Error('再ログインしてください。'); return { Authorization: `Bearer ${data.session.access_token}` }; }
  async function load() { try { const response = await fetch('/api/rpa/admin/job-definitions', { headers: await headers() }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setRows(body.definitions ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : '読み込みに失敗しました。'); } }
  useEffect(() => { void load(); }, []);
  async function save(row: Definition) { try { const response = await fetch('/api/rpa/admin/job-definitions', { method: 'PATCH', headers: { 'Content-Type': 'application/json', ...(await headers()) }, body: JSON.stringify({ id: row.id, is_enabled: row.is_enabled, schedule: row.schedule }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setMessage('保存しました。'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : '保存に失敗しました。'); } }
  return <main className="mx-auto max-w-5xl space-y-5 p-4"><header><h1 className="text-xl font-bold">RPA Job定義・定時実行</h1><p className="mt-1 text-sm text-gray-600">有効化前に、Runner管理画面で必ずSMS送信なしのテスト実行を確認してください。</p></header>{message && <p className="rounded border bg-blue-50 p-3 text-sm">{message}</p>}<section className="overflow-x-auto rounded border bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50"><tr>{['表示名','実行方式 / 起動','実行時刻（JST）','有効','最終Job生成','保存'].map((label) => <th key={label} className="px-3 py-2">{label}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t"><td className="px-3 py-2"><div className="font-medium">{row.name}</div><code className="text-xs">{row.job_type}</code></td><td className="px-3 py-2">{row.execution_mode} / {row.trigger_type}</td><td className="px-3 py-2"><input className="w-24 rounded border px-2 py-1" value={row.schedule.times?.[0] ?? ''} onChange={(event) => setRows((current) => current.map((item) => item.id === row.id ? { ...item, schedule: { timezone: 'Asia/Tokyo', times: [event.target.value] } } : item))} placeholder="10:00" /></td><td className="px-3 py-2"><input type="checkbox" checked={row.is_enabled} onChange={(event) => setRows((current) => current.map((item) => item.id === row.id ? { ...item, is_enabled: event.target.checked } : item))} /></td><td className="px-3 py-2">{row.last_generated_at ? new Date(row.last_generated_at).toLocaleString('ja-JP') : '—'}</td><td className="px-3 py-2"><button className="rounded border px-3 py-1" onClick={() => void save(row)}>保存</button></td></tr>)}</tbody></table></section></main>;
}
