"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
type Row = { user_id:string; staff_name:string; removed:boolean; lineworks_exists:boolean; last_shift_date:string|null; inactive_days:number|null; reasons:string[]; action:"mark-removed"|"delete-lineworks"|"retire" };
export default function StaffRetirementReview() {
 const [rows,setRows]=useState<Row[]>([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);setError("");const {data}=await supabase.auth.getSession();const r=await fetch("/api/admin/staff-retirement-review",{headers:{Authorization:`Bearer ${data.session?.access_token??""}`}});const j=await r.json();if(!r.ok)setError(j.error??"取得に失敗しました");else setRows(j.rows);setLoading(false)};
 const run=async(row:Row)=>{const labels={"mark-removed":"Myファミーユを退職扱いにする","delete-lineworks":"LINE WORKSから削除","retire":"退職処理"};if(!confirm(`${row.staff_name} を${labels[row.action]}しますか？`))return;setLoading(true);const {data}=await supabase.auth.getSession();const r=await fetch("/api/admin/staff-retirement-review",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session?.access_token??""}`},body:JSON.stringify({user_id:row.user_id,action:row.action})});const j=await r.json();if(!r.ok){setError(j.error??"処理に失敗しました");setLoading(false);return;}await load();};
 useEffect(()=>{void load()},[]);
 return <Card><CardHeader><CardTitle>職員稼働・退職整合性管理</CardTitle></CardHeader><CardContent className="space-y-3"><Button onClick={()=>void load()} disabled={loading}>{loading?"読込中...":"更新"}</Button>{error&&<p className="text-sm text-red-600">{error}</p>}<div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>user_id</TableHead><TableHead>職員</TableHead><TableHead>Myファミーユ</TableHead><TableHead>LINE WORKS</TableHead><TableHead>最終稼働</TableHead><TableHead>未稼働</TableHead><TableHead>判定</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.user_id}><TableCell>{r.user_id}</TableCell><TableCell>{r.staff_name}</TableCell><TableCell>{r.removed?"退職扱い":"在籍"}</TableCell><TableCell>{r.lineworks_exists?"登録あり":"登録なし"}</TableCell><TableCell>{r.last_shift_date??"—"}</TableCell><TableCell>{r.inactive_days===null?"—":`${r.inactive_days}日`}</TableCell><TableCell>{r.reasons.join(" / ")}</TableCell><TableCell><Button size="sm" onClick={()=>void run(r)} disabled={loading}>{r.action==="mark-removed"?"退職扱いにする":r.action==="delete-lineworks"?"LWから削除":"退職処理"}</Button></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>;
}
