create table if not exists public.regular_shift_requests (
  id bigint generated by default as identity primary key,
  user_id text not null,
  weekly_shift_id bigint not null references public.shift(shift_id) on delete restrict,
  source_shift_id bigint not null references public.shift(shift_id) on delete restrict,
  requested_at timestamptz not null default now(),
  available_from_month date not null,
  status text not null default 'requested' check (status in ('requested', 'approved', 'rejected', 'cancelled')),
  lineworks_notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint regular_shift_requests_user_weekly_unique unique (user_id, weekly_shift_id),
  constraint regular_shift_requests_source_not_weekly check (source_shift_id <> weekly_shift_id)
);

create index if not exists regular_shift_requests_user_status_idx
  on public.regular_shift_requests (user_id, status);
create index if not exists regular_shift_requests_weekly_shift_idx
  on public.regular_shift_requests (weekly_shift_id);

alter table public.regular_shift_requests enable row level security;

comment on table public.regular_shift_requests is 'シフ子から申請された週間シフトのレギュラー希望';
