-- 祝日休み設定・祝日対応履歴
alter table public.shift_weekly_template
  add column if not exists holiday_off boolean not null default false;

create table if not exists public.holiday_master (
  id bigint generated by default as identity primary key,
  holiday_date date not null unique,
  holiday_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.holiday_shift_action (
  id bigint generated by default as identity primary key,
  holiday_date date not null,
  weekly_shift_id bigint not null references public.shift_weekly_template(template_id) on delete cascade,
  shift_id bigint references public.shift(shift_id) on delete set null,
  client_id text not null,
  status text not null default 'pending' check (status in ('pending','deleted','keep','changed','no_shift')),
  action_note text,
  processed_by uuid,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint holiday_shift_action_identity unique (holiday_date, weekly_shift_id, shift_id)
);

create index if not exists holiday_master_active_date_idx on public.holiday_master(holiday_date) where is_active;
create index if not exists holiday_shift_action_lookup_idx on public.holiday_shift_action(holiday_date, weekly_shift_id, shift_id, status);

alter table public.holiday_master enable row level security;
alter table public.holiday_shift_action enable row level security;

drop policy if exists holiday_master_read_authenticated on public.holiday_master;
create policy holiday_master_read_authenticated on public.holiday_master for select to authenticated using (true);
drop policy if exists holiday_master_manage_admin_manager on public.holiday_master;
create policy holiday_master_manage_admin_manager on public.holiday_master for all to authenticated
  using (exists (select 1 from public.users u where u.auth_user_id = auth.uid() and lower(coalesce(u.system_role, u.role, '')) in ('admin','manager')))
  with check (exists (select 1 from public.users u where u.auth_user_id = auth.uid() and lower(coalesce(u.system_role, u.role, '')) in ('admin','manager')));

drop policy if exists holiday_shift_action_read_authenticated on public.holiday_shift_action;
create policy holiday_shift_action_read_authenticated on public.holiday_shift_action for select to authenticated using (true);
drop policy if exists holiday_shift_action_manage_admin_manager on public.holiday_shift_action;
create policy holiday_shift_action_manage_admin_manager on public.holiday_shift_action for all to authenticated
  using (exists (select 1 from public.users u where u.auth_user_id = auth.uid() and lower(coalesce(u.system_role, u.role, '')) in ('admin','manager')))
  with check (exists (select 1 from public.users u where u.auth_user_id = auth.uid() and lower(coalesce(u.system_role, u.role, '')) in ('admin','manager')));

comment on column public.shift_weekly_template.holiday_off is '通常曜日は実施するが祝日は原則休み';
