-- rollback_phase_b: restore phase_b table RLS and grants
-- DRAFT: run only in the maintenance window, after backup/Gate checks.
-- Generated from the 2026-08-24 pre-RLS snapshot.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '5min';

REVOKE ALL PRIVILEGES ON TABLE public."cm_select_options" FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."event_task_required_docs" FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."event_template_required_docs" FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."msg_lw_status" FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."service_kinds" FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."shift_record_items" FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public."system_role_master" FROM anon, authenticated;

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT INSERT (category) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT REFERENCES (category) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT SELECT (category) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT UPDATE (category) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT INSERT (code) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT REFERENCES (code) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT SELECT (code) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT UPDATE (code) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT INSERT (created_at) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT REFERENCES (created_at) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT SELECT (created_at) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT UPDATE (created_at) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT INSERT (created_by) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT REFERENCES (created_by) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT SELECT (created_by) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT UPDATE (created_by) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT INSERT (is_active) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT REFERENCES (is_active) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT SELECT (is_active) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT UPDATE (is_active) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT INSERT (label) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT REFERENCES (label) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT SELECT (label) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT UPDATE (label) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT INSERT (requires_input) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT REFERENCES (requires_input) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT SELECT (requires_input) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT UPDATE (requires_input) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT INSERT (sort_order) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT REFERENCES (sort_order) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT SELECT (sort_order) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT UPDATE (sort_order) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT INSERT (updated_at) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT REFERENCES (updated_at) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT SELECT (updated_at) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT UPDATE (updated_at) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT INSERT (updated_by) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT REFERENCES (updated_by) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT SELECT (updated_by) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT UPDATE (updated_by) ON TABLE public.cm_select_options TO anon; -- grantor: postgres
GRANT INSERT (category) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT REFERENCES (category) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT SELECT (category) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT UPDATE (category) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT INSERT (code) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT REFERENCES (code) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT SELECT (code) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT UPDATE (code) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT INSERT (created_at) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT REFERENCES (created_at) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT SELECT (created_at) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT UPDATE (created_at) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT INSERT (created_by) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT REFERENCES (created_by) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT SELECT (created_by) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT UPDATE (created_by) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT INSERT (is_active) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT REFERENCES (is_active) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT SELECT (is_active) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT UPDATE (is_active) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT INSERT (label) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT REFERENCES (label) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT SELECT (label) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT UPDATE (label) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT INSERT (requires_input) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT REFERENCES (requires_input) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT SELECT (requires_input) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT UPDATE (requires_input) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT INSERT (sort_order) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT REFERENCES (sort_order) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT SELECT (sort_order) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT UPDATE (sort_order) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT INSERT (updated_at) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT REFERENCES (updated_at) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT SELECT (updated_at) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT UPDATE (updated_at) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT INSERT (updated_by) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT REFERENCES (updated_by) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT SELECT (updated_by) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT UPDATE (updated_by) ON TABLE public.cm_select_options TO authenticated; -- grantor: postgres
GRANT INSERT (checked_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (checked_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT SELECT (checked_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (checked_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT INSERT (checked_by_user_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (checked_by_user_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT SELECT (checked_by_user_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (checked_by_user_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT INSERT (created_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (created_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT SELECT (created_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (created_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT INSERT (doc_type_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (doc_type_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT SELECT (doc_type_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (doc_type_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT INSERT (event_task_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (event_task_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT SELECT (event_task_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (event_task_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT INSERT (memo) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (memo) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT SELECT (memo) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (memo) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT INSERT (result_doc_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (result_doc_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT SELECT (result_doc_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (result_doc_id) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT INSERT (status) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (status) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT SELECT (status) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (status) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT INSERT (updated_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (updated_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT SELECT (updated_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (updated_at) ON TABLE public.event_task_required_docs TO anon; -- grantor: postgres
GRANT INSERT (checked_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (checked_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (checked_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (checked_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (checked_by_user_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (checked_by_user_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (checked_by_user_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (checked_by_user_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (created_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (created_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (created_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (created_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (doc_type_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (doc_type_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (doc_type_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (doc_type_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (event_task_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (event_task_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (event_task_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (event_task_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (memo) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (memo) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (memo) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (memo) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (result_doc_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (result_doc_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (result_doc_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (result_doc_id) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (status) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (status) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (status) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (status) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (updated_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (updated_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (updated_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (updated_at) ON TABLE public.event_task_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (check_source) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (check_source) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT SELECT (check_source) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (check_source) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT INSERT (created_at) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (created_at) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT SELECT (created_at) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (created_at) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT INSERT (doc_type_id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (doc_type_id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT SELECT (doc_type_id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (doc_type_id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT INSERT (memo) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (memo) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT SELECT (memo) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (memo) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT INSERT (sort_order) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (sort_order) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT SELECT (sort_order) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (sort_order) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT INSERT (template_id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (template_id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT SELECT (template_id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (template_id) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT INSERT (updated_at) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT REFERENCES (updated_at) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT SELECT (updated_at) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT UPDATE (updated_at) ON TABLE public.event_template_required_docs TO anon; -- grantor: postgres
GRANT INSERT (check_source) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (check_source) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (check_source) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (check_source) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (created_at) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (created_at) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (created_at) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (created_at) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (doc_type_id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (doc_type_id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (doc_type_id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (doc_type_id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (memo) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (memo) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (memo) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (memo) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (sort_order) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (sort_order) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (sort_order) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (sort_order) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (template_id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (template_id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (template_id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (template_id) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (updated_at) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT REFERENCES (updated_at) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT SELECT (updated_at) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT UPDATE (updated_at) ON TABLE public.event_template_required_docs TO authenticated; -- grantor: postgres
GRANT INSERT (description) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT REFERENCES (description) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT SELECT (description) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT UPDATE (description) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT INSERT (label) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT REFERENCES (label) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT SELECT (label) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT UPDATE (label) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT INSERT (sort_order) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT REFERENCES (sort_order) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT SELECT (sort_order) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT UPDATE (sort_order) ON TABLE public.msg_lw_status TO anon; -- grantor: postgres
GRANT INSERT (description) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT REFERENCES (description) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT SELECT (description) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT UPDATE (description) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT INSERT (label) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT REFERENCES (label) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT SELECT (label) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT UPDATE (label) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT INSERT (sort_order) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT REFERENCES (sort_order) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT SELECT (sort_order) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT UPDATE (sort_order) ON TABLE public.msg_lw_status TO authenticated; -- grantor: postgres
GRANT INSERT (created_at) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT REFERENCES (created_at) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT SELECT (created_at) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT UPDATE (created_at) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT INSERT (label) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT REFERENCES (label) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT SELECT (label) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT UPDATE (label) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT INSERT (sort_order) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT REFERENCES (sort_order) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT SELECT (sort_order) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT UPDATE (sort_order) ON TABLE public.service_kinds TO anon; -- grantor: postgres
GRANT INSERT (created_at) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT REFERENCES (created_at) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT SELECT (created_at) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT UPDATE (created_at) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT INSERT (label) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT REFERENCES (label) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT SELECT (label) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT UPDATE (label) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT INSERT (sort_order) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT REFERENCES (sort_order) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT SELECT (sort_order) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT UPDATE (sort_order) ON TABLE public.service_kinds TO authenticated; -- grantor: postgres
GRANT INSERT (created_at) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT REFERENCES (created_at) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT SELECT (created_at) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT UPDATE (created_at) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT INSERT (item_def_id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT REFERENCES (item_def_id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT SELECT (item_def_id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT UPDATE (item_def_id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT INSERT (note) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT REFERENCES (note) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT SELECT (note) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT UPDATE (note) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT INSERT (record_id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT REFERENCES (record_id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT SELECT (record_id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT UPDATE (record_id) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT INSERT (updated_at) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT REFERENCES (updated_at) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT SELECT (updated_at) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT UPDATE (updated_at) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT INSERT (value_text) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT REFERENCES (value_text) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT SELECT (value_text) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT UPDATE (value_text) ON TABLE public.shift_record_items TO anon; -- grantor: postgres
GRANT INSERT (created_at) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT REFERENCES (created_at) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT SELECT (created_at) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT UPDATE (created_at) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT INSERT (item_def_id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT REFERENCES (item_def_id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT SELECT (item_def_id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT UPDATE (item_def_id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT INSERT (note) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT REFERENCES (note) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT SELECT (note) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT UPDATE (note) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT INSERT (record_id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT REFERENCES (record_id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT SELECT (record_id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT UPDATE (record_id) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT INSERT (updated_at) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT REFERENCES (updated_at) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT SELECT (updated_at) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT UPDATE (updated_at) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT INSERT (value_text) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT REFERENCES (value_text) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT SELECT (value_text) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT UPDATE (value_text) ON TABLE public.shift_record_items TO authenticated; -- grantor: postgres
GRANT INSERT (active) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT REFERENCES (active) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT SELECT (active) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT UPDATE (active) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT INSERT (description) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT REFERENCES (description) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT SELECT (description) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT UPDATE (description) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT INSERT (label) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT REFERENCES (label) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT SELECT (label) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT UPDATE (label) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT INSERT (sort_order) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT REFERENCES (sort_order) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT SELECT (sort_order) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT UPDATE (sort_order) ON TABLE public.system_role_master TO anon; -- grantor: postgres
GRANT INSERT (active) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT REFERENCES (active) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT SELECT (active) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT UPDATE (active) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT INSERT (description) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT REFERENCES (description) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT SELECT (description) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT UPDATE (description) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT INSERT (id) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT REFERENCES (id) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT SELECT (id) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT UPDATE (id) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT INSERT (label) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT REFERENCES (label) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT SELECT (label) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT UPDATE (label) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT INSERT (sort_order) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT REFERENCES (sort_order) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT SELECT (sort_order) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres
GRANT UPDATE (sort_order) ON TABLE public.system_role_master TO authenticated; -- grantor: postgres

ALTER TABLE public.cm_select_options DISABLE ROW LEVEL SECURITY; ALTER TABLE public.cm_select_options NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.event_task_required_docs DISABLE ROW LEVEL SECURITY; ALTER TABLE public.event_task_required_docs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.event_template_required_docs DISABLE ROW LEVEL SECURITY; ALTER TABLE public.event_template_required_docs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.msg_lw_status DISABLE ROW LEVEL SECURITY; ALTER TABLE public.msg_lw_status NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.service_kinds DISABLE ROW LEVEL SECURITY; ALTER TABLE public.service_kinds NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.shift_record_items DISABLE ROW LEVEL SECURITY; ALTER TABLE public.shift_record_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.system_role_master DISABLE ROW LEVEL SECURITY; ALTER TABLE public.system_role_master NO FORCE ROW LEVEL SECURITY;
COMMIT;
